"""tables

Revision ID: 9eb62fcdcef4
Revises: 
Create Date: 2023-07-11 22:55:05.680300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb62fcdcef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provisional_diagnosis', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['provisional_diagnosis'])
        batch_op.create_foreign_key('provisional_diagnosis', 'user_forms', ['provisional_diagnosis'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_forms', schema=None) as batch_op:
        batch_op.drop_constraint('provisional_diagnosis', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('provisional_diagnosis')

    # ### end Alembic commands ###
